// Test helper: rebuilds the benchmark reference session (reference-harness sim/scenario.py + agent_client.py)
// from test/fixtures/sim-history.json.gz (generated by scripts/tokenizer/gen_template_goldens.py).
// The SIM_CAP_BYTES truncation and SIM_CHATTY text are ported from scenario.py tool_output() / _text().
import { readFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { join } from 'node:path';
import type { ChatMessage, ChatRequest } from '../../src/types.js';
import { ROOT } from '../helpers.js';

export interface SimHistory {
  system: string;
  goal: string;
  tools: unknown[];
  inject: Record<string, string>;
  chatty: string;
  steps: Array<{ content: string | null; id: string; name: string; arguments: string; output: string }>;
}

let cached: SimHistory | null = null;
export function loadSimHistory(): SimHistory {
  cached ??= JSON.parse(gunzipSync(readFileSync(join(ROOT, 'test', 'fixtures', 'sim-history.json.gz'))).toString('utf8')) as SimHistory;
  return cached;
}

export interface SimEnv {
  cap?: number | null;
  chatty?: boolean;
}

/** scenario.tool_output(): OpenCode-style head truncation at `cap` UTF-8 bytes. */
export function capOutput(out: string, step: number, cap: number): string {
  const lines = out.split('\n');
  const kept: string[] = [];
  let size = 0;
  for (let i = 0; i < Math.min(lines.length, 2000); i++) {
    const b = Buffer.byteLength(lines[i]!, 'utf8') + (i ? 1 : 0);
    if (size + b > cap) break;
    kept.push(lines[i]!);
    size += b;
  }
  if (kept.length === lines.length) return out;
  const removed = Buffer.byteLength(out, 'utf8') - size;
  return (
    kept.join('\n') +
    `\n\n...${removed} bytes truncated...\n\nThe tool call succeeded but the output was truncated. Full output saved to: /users/example/.local/share/opencode/tool-output/` +
    `tool_${String(step).padStart(4, '0')}\nUse Grep to search the full content or Read with offset/limit to view specific sections.`
  );
}

/** agent_client.py history after `steps` steps. */
export function simMessages(h: SimHistory, steps: number, env: SimEnv = {}): ChatMessage[] {
  const msgs: ChatMessage[] = [
    { role: 'system', content: h.system },
    { role: 'user', content: h.goal },
  ];
  for (let s = 0; s < steps; s++) {
    const st = h.steps[s]!;
    let content = st.content;
    if (env.chatty && s !== 2 && s !== 14) content = (content || 'Continuing.') + h.chatty;
    msgs.push({
      role: 'assistant',
      content,
      tool_calls: [{ id: st.id, type: 'function', function: { name: st.name, arguments: st.arguments } }],
    });
    msgs.push({ role: 'tool', tool_call_id: st.id, content: env.cap ? capOutput(st.output, s, env.cap) : st.output });
    const inj = h.inject[String(s)];
    if (inj !== undefined) msgs.push({ role: 'user', content: inj });
  }
  return msgs;
}

/** The client's request body at a step (same key order as agent_client.py). */
export function simRequest(h: SimHistory, steps: number, env: SimEnv = {}): ChatRequest {
  return {
    model: 'local-model',
    messages: simMessages(h, steps, env),
    tools: h.tools,
    max_tokens: 32000,
    stream: true,
    stream_options: { include_usage: true },
  };
}
