// Dev tool: copies the Python-generated golden vectors from the reference study into gzipped test
// fixtures under test/fixtures/bench/.
//
//   node dist/bench/tools/make-fixtures.js <notes-dir> [<sim-port-tmp-dir>]
//
// <notes-dir> holds pyrandom_vectors.json, pyjson_vectors.json, scenario_golden.json,
// render_golden.json and mock_http_golden.json (generated by gen_*.py / capture_mock.py with CPython
// 3.14.7 and tokenizers 0.23.2). <sim-port-tmp-dir> optionally holds ot_*.json / otf_*.json: per-step
// orig_qwen_tokens / orig_est_tokens of the uncompacted client history (orig_totals.py).

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { gzipSync } from 'node:zlib';
import { ROOT } from '../lib/paths.js';

const [notes, simPort] = process.argv.slice(2);
if (!notes) {
  console.error('usage: make-fixtures.js <notes-dir> [<sim-port-tmp-dir>]');
  process.exit(2);
}
const out = join(ROOT, 'test', 'fixtures', 'bench');
mkdirSync(out, { recursive: true });
let total = 0;
const put = (name: string, text: string): void => {
  const gz = gzipSync(Buffer.from(text, 'utf8'), { level: 9 });
  writeFileSync(join(out, name), gz);
  total += gz.length;
  console.log(`${name}: ${text.length} chars -> ${gz.length} bytes`);
};
for (const [src, dst] of [
  ['pyrandom_vectors.json', 'pyrandom.json.gz'],
  ['pyjson_vectors.json', 'pyjson.json.gz'],
  ['scenario_golden.json', 'scenario.json.gz'],
  ['render_golden.json', 'render.json.gz'],
  ['mock_http_golden.json', 'mock_http.json.gz'],
] as const) {
  // Round-trip through JSON.parse to drop pretty-printing whitespace; content is unchanged.
  put(dst, JSON.stringify(JSON.parse(readFileSync(join(notes, src), 'utf8'))));
}
if (simPort) {
  const counts: Record<string, unknown> = {};
  for (const f of ['ot_uncapped', 'ot_cap51200', 'ot_cap50000', 'otf_chatty_cap51200_46', 'otf_huge150_20']) {
    const p = join(simPort, f + '.json');
    if (!existsSync(p)) continue;
    const j = JSON.parse(readFileSync(p, 'utf8')) as Record<string, unknown>;
    counts[f] = { env: j['env'], steps: j['steps'], per_step: j['per_step'], per_step_est: j['per_step_est'] };
  }
  put('counts.json.gz', JSON.stringify(counts));
  // baseline.py stdout (reruns, byte-identical to reference-harness/results/baseline_*.md where one exists)
  const baseline: Record<string, string> = {};
  for (const v of ['cap51200', 'uncapped', 'cap51200_s3000', 'cap50000']) {
    const p = join(simPort, 'rerun', `baseline_${v}.md`);
    if (existsSync(p)) baseline[v] = readFileSync(p, 'utf8');
  }
  put('baseline.json.gz', JSON.stringify(baseline));
}
console.log(`total ${total} bytes`);
